### ISSUE TITLE
Tracking issue: support for describing 100% of Miden VM constraints in AirScript

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#162]
### Goal(s)
- be able to describe 100% of Miden VM constraints in AirScript in a clean, modular way.

### Details

We need to finish basic list comprehension, which was added to the parser but not yet to the IR. The final piece of functionality we need in order to write all Miden VM constraints in AirScript is support for variable-length public inputs, as described in #143. After adding this, we will also ideally add support for list comprehension for lists of variable size (this applies only to boundary constraints as variable-sized lists are possible only for public inputs)

While adding this support would give us the ability to define all constraints, we can't do so in a clean, sane, and maintainable way until we have support for modularity. At a minimum, we need support for module imports, evaluators, and selectors. Pure functions would be nice to have as well

```[tasklist]
### Must have
- [ ] https://github.com/0xPolygonMiden/air-script/issues/87
- [ ] https://github.com/0xPolygonMiden/air-script/issues/153
- [ ] https://github.com/0xPolygonMiden/air-script/issues/150
- [ ] https://github.com/0xPolygonMiden/air-script/issues/143
- [ ] https://github.com/0xPolygonMiden/air-script/issues/122
- [ ] https://github.com/0xPolygonMiden/air-script/issues/124
- [ ] https://github.com/0xPolygonMiden/air-script/issues/125
```

```[tasklist]
### Nice to have
- [ ] https://github.com/0xPolygonMiden/air-script/issues/123
- [ ] https://github.com/0xPolygonMiden/air-script/issues/163
- [ ] https://github.com/0xPolygonMiden/air-script/issues/186
- [ ] #217
```

## Working group:
@Al-Kindi-0, @grjte, @Overcastan, @tohrnii 

<details>
<summary>Workflow</summary>
    
- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
    
</details>

### Coordinator: @tohrnii
<details>
    
The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by bobbinth** [comment]
Closing this as most must-haves have been addresses, and variable-length public inputs is carried over into the next milestone.
